### ISSUE TITLE
ARM Template for Infra deployment (Synapse, ADF, etc)?

### ISSUE THREAD

**Issue by DeepMalh44** [kunal333/E2ESynapseDemo#4]
Hi Kunal,
Thank you for this demo and the scripts. I had a quick question on why did you chose to go with PS1 scripts for creating the Azure Snypase, SQL Server and the ADF instances? Do you see any issue with those being deployed from ARM Template sameway as the data pipelines, flows, datasets, etc. are getting deployed as part of this demo? Any plans to have ARM template for the infra components (Synapse, ADF, etc.).

Thank you!

**Comment by kunal333** [comment]
Hi there!
Thanks for trying on the CMS project and providing feedback.  In my first attempt, I was interested in learning PowerShell and thus was using code to deploy infra.  However, I took your suggestion and made changes to the code where I'm now using ARM templates to deploy the infra.  Try this latest version (with upgrade from SQL DW to Synapse Analytics) and do provide feedback.
Thanks!
Kunal
